/**FileController Class
  * This class controls the loading/saving file operations
  * 
  * @author Shaheer Majeed
  * @since January 22, 2023
  */

import java.io.*;
import javax.swing.*;
import java.awt.event.*;

public class FileController implements ActionListener
{
     //instance variables
     private Model2048 model;              //The model attached to the controller
     private GUI2048 view;                 //The view attached to the controller
     private JFileChooser fileChooser;     //The JFileChooser object attached to the controller
     
     /**Constructor for FileController object
       * @param aModel -------- The model the controller is attached to
       * @param aView --------- The view the controller is attached to
       * @param aFileChooser -- The file chooser object the controller is attached to
       */
     public FileController (Model2048 aModel, GUI2048 aView, JFileChooser aFileChooser)
     {
          this.model = aModel;
          this.view = aView;
          this.fileChooser = aFileChooser;
     }//End of FileController constructor
     
     /**Triggers actions when the load file button is used
       * @param e The ActionEvent generated by the component used
       */
     public void actionPerformed (ActionEvent e)
     {
          //opens a dialog for the user to select a file to open
          int fileSelected = fileChooser.showOpenDialog (view);
          
          //if user selects a file, loads data from the file via loadResults() method
          if (fileSelected == JFileChooser.APPROVE_OPTION) {   
               File aFile = fileChooser.getSelectedFile();    
               this.model.loadResults(aFile);                 
          }
     }//End of actionPerformed method
     
}//End of FileController class