/**MoveController Class
  * this class processes button inputs
  *
  * @author Shaheer Majeed
  * @since January 22, 2023
  */

import java.io.*;
import javax.swing.*;
import java.awt.event.*;

public class MoveController implements ActionListener
{
     //instance variables
     private Model2048 model; //The model attatched to the controller
     
     /**Constructor for MoveController object
       * @param aModel The model the controller is attatched to
       */
     public MoveController (Model2048 aModel)
     {
          this.model = aModel;
     } //End of MoveController constructor
     
     /**Triggers actions when movement buttons are used
       * @param e The ActionEvent generated by the component used
       */
     public void actionPerformed (ActionEvent e)
     {
          this.model.processMove(e.getActionCommand());
     } //End of actionPerformed method
     
} //MoveController class