/**NewGameController Class
  * This class processes the newGame button to start a new game
  *
  * @author Shaheer Majeed
  * @since January 22, 2023
  */

import javax.swing.*;
import java.awt.event.*;

public class NewGameController implements ActionListener
{
     //instance variables
     private Model2048 model;        //The model attached to the controller
     private JPanel userDataPanel;   //The panel with the users information
     private JButton userInput;      //The OK button with the users input
     private JLabel status;          //The status label after a game
     private JTabbedPane pane;       //The JTabbedPane object of leaderboard and results
     
     /**Constructor for NewGameController object
       * @param aModel ---------- The model the controller is attatched to
       * @param aUserDataPanel -- The panel with the users information
       * @param aUserInput ------ The button pressed after user inputs data
       * @param sStatus --------- The win/loss status of the game
       * @param aPane ----------- The Tabbed Pane with the leaderboard and results
       */
     public NewGameController (Model2048 aModel, JPanel aUserDataPanel, JButton aUserInput, JLabel aStatus, JTabbedPane aPane)
     {
          this.model = aModel;
          this.userDataPanel = aUserDataPanel;
          this.userInput = aUserInput;
          this.status = aStatus;
          this.pane = aPane;
     }//End of NewGameController constructor
     
     /**Triggers actions when the new game button is used
       * @param e The ActionEvent generated by the component used
       */
     public void actionPerformed (ActionEvent e)
     {
          this.model.resetGame();
          this.model.setButtonsEnabled(false);
          this.userDataPanel.setVisible(true);
          this.status.setVisible(false);
          this.userInput.setEnabled(true);
          this.pane.setSelectedIndex(1);
     }//End of actionPerformed method
     
}//End of NewGameController class