/**QuitController Class
  * this class exits the program
  *
  * @author Shaheer Majeed
  * @since January 22, 2023
  */

import java.awt.event.*;

public class QuitController implements ActionListener
{
     //instance variables
     private Model2048 model; //The model attached to the controller
     
     /**Constructor for FileController object
       * @param aModel - The model the controller is attached to
       */
     public QuitController (Model2048 aModel)
     {
          this.model = aModel;
     }//End of QuitController constructor
     
     /**Triggers actions when the quit button is used
       * @param e The ActionEvent generated by the component used
       */
     public void actionPerformed (ActionEvent e)
     {
          System.exit(1);
     }//End of actionPerformed method
     
} //QuitController class