/**WASDController Class
 * This class processes key press inputs for 2048.
 *
 * @author Shaheer Majeed
 * @since January 22, 2023
*/

import javax.swing.*;
import java.awt.event.*;

public class WASDController implements KeyListener
{
     //instance variables
     private Model2048 model; //the model attatched to the controller
     
     /**Constructor for WASDController object
       * @param aModel The model the controller is attatched to
       */
     public WASDController (Model2048 aModel)
     {
          this.model = aModel;
     } //end of MoveController constructor
     
     /**Triggers actions when movement buttons are used
       * @param e The KeyEvent generated by the component used
       */
     public void keyPressed (KeyEvent e)
     {
          char pressedC = e.getKeyChar(); //stores the character pessed
          int pressedI = e.getKeyCode();  //stores the key code of the character pressed
          
          //allows key presses to activates moves if the game has been started and round has not been lost
          if (this.model.getRoundNum() != 0 && this.model.getLossState() == false) {
               if (pressedC == 'w' || pressedC == 'W' || pressedI == KeyEvent.VK_UP)
                    this.model.processMove("Up");
               if (pressedC == 'a' || pressedC == 'A' || pressedI == KeyEvent.VK_LEFT)
                    this.model.processMove("Left");
               if (pressedC == 's' || pressedC == 'S' || pressedI == KeyEvent.VK_DOWN)
                    this.model.processMove("Down");
               if (pressedC == 'd' || pressedC == 'D' || pressedI == KeyEvent.VK_RIGHT)
                    this.model.processMove("Right");
          }
     } //end of keyPressed method
     
     //unused method required by the KeyListener interface
     public void keyReleased (KeyEvent e)
     {}
     
     //unused method required by the KeyListener interface
     public void keyTyped (KeyEvent e)
     {}
     
} //WASDController class